config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :contacts, except: [:index]
  end
  resources :messages, only: [:new, :create, :show]
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_many :messages
  belongs_to :user
  validates :phone, presence: true
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  # after_validation :normalize_phone_number

  def normalize_phone_number
    self.phone.gsub!(/[^0-9]/, "")
    if self.phone.length == 11 && self.phone.first == "1"
      self.phone = self.phone[1..10]
    end
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :contact
  before_create :send_sms

private
  def send_sms
    begin
      response = RestClient::Request.new(
        method: :post,
        url: "https://api.twilio.com/2010-04-01/Accounts/#{ENV['TWILIO_ACCOUNT_SID']}/Messages.json",
        user: ENV['TWILIO_ACCOUNT_SID'],
        password: ENV['TWILIO_AUTH_TOKEN'],
        payload: { Body: body, To: to, From: from }
      ).execute
    rescue RestClient::BadRequest => error
      message = JSON.parse(error.response)['message']
      errors.add(:base, message)
      false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :contacts
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   # Virtual attribute for authenticating by either username or email
   # This is in addition to a real persisted field like 'username'
   attr_accessor :login

   def self.find_first_by_auth_conditions(warden_conditions)
     conditions = warden_conditions.dup
     if login = conditions.delete(:login)
       where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
     else
       if conditions[:username].nil?
         where(conditions).first
       else
         where(username: conditions[:username]).first
       end
     end
   end

   validates :username, :presence => true, :uniqueness => { :case_sensitive => false }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def authenticate_user
    unless user_signed_in?
      flash[:alert] = "You must be signed in to do that."
      redirect_to new_user_session_path
    end
  end

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me, :avatar) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password, :avatar) }
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_action :authenticate_user

  def show
    @contact = Contact.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @contact = Contact.new
  end

  def create

    @contact = current_user.contacts.new(contact_params)
    @user = current_user

    @contact.normalize_phone_number
    existing_contact = @user.contacts.find_by(phone: @contact.phone)

    if existing_contact
      flash[:alert] = "This contact is already in your phone book!"
      render 'new'
    else
      if @contact.save
        flash[:notice] = "Contact saved!"
        redirect_to user_path(current_user)
      else
        flash[:alert] = "Some kind of error."
        render 'new'
      end
    end
    
  end

  def edit
    @contact = Contact.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def update
    @contact = Contact.find(params[:id])
    @user = User.find(params[:user_id])
    if @contact.update(contact_params)
      flash[:notice] = @contact.name + " has been successfully edited."
      redirect_to user_contact_path(@user, @contact)
    else
      render "edit"
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @user = User.find(params[:user_id])
    flash[:notice] = @contact.name + " has been deleted from your life."
    @contact.destroy
    redirect_to user_path(@user)
  end

private
  def contact_params
    params.require(:contact).permit(:name, :phone, :avatar)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :authenticate_user

  def index
    @messages = Message.all
  end

  def show
    @message = Message.find(params[:id])
  end

  def new
    unless params[:phone] == nil
      @contact = Contact.find_by(phone: params[:phone])
      render :new_from_existing_phone
    else
      render :new
    end
  end

  def create
    from = ENV['FROM_PHONE_NUMBER']
    body = params[:body]
    recipients = params[:to].split
    failures = []

    recipients.each do |recipient|
      msg = Message.new(from: from, body: body, to: recipient)
      msg.contact = Contact.find_or_initialize_by(phone: msg.to)
      msg.contact.user = current_user
      unless msg.save
        failures.push(recipient)
      end
    end

    if failures.length > 0
      the_failures = failures.join(", ")
      flash[:alert] = "SMS failed to send to the following recipients: " + the_failures
    else
      flash[:notice] = "Woohoo!"
    end
    redirect_to user_path(current_user)
  end

private
  def message_params
    params.require(:message).permit(:to, :body).merge(from: ENV['FROM_PHONE_NUMBER'])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user, only: [:show]

  def index
    if user_signed_in?
      redirect_to user_path(current_user)
    else
      redirect_to new_user_session_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_contact.html.erb
<p>
  <% unless contact.name == "" %>
    <%= link_to contact.name, user_contact_path(contact.user, contact) %>
  <% else %>
    <%= link_to contact.phone, user_contact_path(contact.user, contact) %>
  <% end %>
</p>

app/views/contacts/_form.html.erb
<%= bootstrap_form_for [@user, @contact] do |f| %>
  <div class="field">
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.telephone_field :phone %>
  </div>

  <div class="field">
    <%= f.file_field :avatar %>
  </div>

  <div class="actions">
    <%= f.submit "Save Contact" %>
  </div>
<% end %>

app/views/contacts/_message.html.erb
<li><%= message.body %></li>

app/views/contacts/edit.html.erb
<h2>Edit Contact</h2>

<%= render 'form' %>

app/views/contacts/new.html.erb
<h2>Add a Contact</h2>

<%= render 'form' %>

app/views/contacts/show.html.erb
<h1><%= @contact.name %></h1>

<% if @contact.avatar_file_name %>
  <%= image_tag @contact.avatar.url(:thumb) %>
<% end %>

<h3><%= link_to @contact.phone, new_message_path({phone: @contact.phone}) %></h3>
<%= link_to "Edit", edit_user_contact_path(@contact.user, @contact) %> |
<%= link_to "Delete", user_contact_path(@contact.user, @contact), method: :delete %>

<h3>Message History</h3>
<ul class="list-unstyled">
  <%= render @contact.messages %>
</ul>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Texter</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li>

        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Create a Contact", new_user_contact_path(current_user) %></li>
          <li><%= link_to "Send a Message", new_message_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <%= current_user.username %><span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Profile", user_path(current_user) %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Texter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash' %>
    <%= yield %>
  </div>

</body>
</html>

app/views/messages/_message.html.erb
<p><%= message.body %></p>

app/views/messages/new.html.erb
<h2>Send an SMS</h2>

<%= form_tag( "/messages", method: "post" ) do %>
  <div class="form-group">
    <%= label_tag "To" %><br>
    <%= telephone_field_tag :to, nil, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag "Body" %><br>
    <%= text_field_tag :body, nil, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= submit_tag "Send", :class => "btn btn-default" %>
  </div>
<% end %>

app/views/messages/new_from_existing_phone.erb
<h2>Send an SMS</h2>

<%= form_tag( "/messages", method: "post" ) do %>

  <%= hidden_field_tag :to, @contact.phone %>

  <div class="form-group">
    <%= label_tag "Body" %><br>
    <%= text_field_tag :body, nil, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= submit_tag "Send", :class => "btn btn-default" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<p><%= link_to user.username, user_path(user) %></p>

app/views/users/index.html.erb
<%= render @users %>

app/views/users/show.html.erb
  <header>
    <h1><%= @user.username %></h1>
    <address><%= @user.email %></address>
    <% if @user.avatar_file_name %>
      <%= image_tag @user.avatar.url(:thumb) %>
    <% end %>
  </header>
  <p><%= link_to "Edit your profile", edit_user_registration_path %></p>
  <section>
    <h2>Contacts</h2>
    <%= render @user.contacts %>
  </section>